### ISSUE TITLE
Copy & paste text - different section is copied (misalignment?)

### ISSUE THREAD

**Issue by stebiger** [coopermaruyama/apathy-theme#16]
When copy & paste some code from atom to my browser I notice that in some cases a compeletely different part of my line is copied in respect of what I marked.

Setting font size to 15 (as I have seen on your gitter) seemed to fix the issue - I report this as I am unsure if it has anything to do with what you reported in that misalignment bug.

**Comment by czxtm** [comment]
Thanks for reporting. First, I just pushed a bunch of new improvements which might have fixed this. Please let me know if it happens again. Can you remember if this happened on a file which already had an open tab when you launched atom, or was the file opened _after_ atom launched?

**Comment by stebiger** [comment]
Sorry I can not remember exacty if it was opened during launch or after.

**Comment by czxtm** [comment]
Alright, let's just hope the new changes fixed this. I'm going to close this for now, let's see if you experience this issue again, in which case please re-open this issue so I can look into it.

Also, if you do get this issue again, please include the debug log that was  implemented in recent updates. To get the debug log, open the console in atom (cmd + alt + I) and run the following:

```
var apathy = atom.packages.getActivePackage('apathy-theme').mainModule;
apathy.apathyView.getDebugLog();
```

**Comment by stebiger** [comment]
Sure I will.
Just made some quick test earlier today and used different font sizes - copy & paste was working nicely.
