### ISSUE TITLE
Apathy Theme causes minimap to put weird gradient in front of text

### ISSUE THREAD

**Issue by rszemplinski** [coopermaruyama/apathy-theme#26]
So I have discovered this weird bug using apathy theme and minimap where this weird rectangle gradient thing pops up when using minimap.

Here is a picture to show the issue:
![image](https://cloud.githubusercontent.com/assets/5331990/11765212/ae4c4a26-a11b-11e5-924a-1bc2285e0692.png)

**Comment by ghost** [comment]
Is this in Atom Dark theme ? Though recommended, I would advise to move to Atom Material UI theme.

**Comment by czxtm** [comment]
Does this happen in dev mode, too? What theme are you using?
