### ISSUE TITLE
update the stylesheet.

### ISSUE THREAD

**Issue by Elmapul** [coopermaruyama/apathy-theme#30]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.

here the colors arent working for html and the hollow/shadow stuff isnt working at all.

**Comment by czxtm** [comment]
I'm aware of this. This theme is no longer "supported" and probably not worth using. The same styles (+ updates) have been moved here: https://atom.io/themes/vivid
