### ISSUE TITLE
Configurable Base Theme Color?

### ISSUE THREAD

**Issue by dvdzkwsk** [coopermaruyama/apathy-theme#9]
Hey, first off I'd like to thank you for your hard work developing this theme. The syntax highlighting is absolutely amazing, and as a JS-dev this is definitely a new favorite. That said, the theme's UI is _incredibly_ purple. Is there any chance you could add some configuration options to alter this? I'm using One Dark as recommended, but it (and other popular themes such as Isotope UI) always end up being super purple when used with Apathy.

I'm fairly inexperienced when it comes to configuring/theming Atom, so maybe this is easier to fix in the user stylesheet than I think, but I thought others might have similar impressions.

Thanks!

**Comment by czxtm** [comment]
Thanks! I had been planning on this for a while and you actually inspired me to do it, hah. The thing is this is not actually possible as I found out (see the notes in the updated README) but I used a hacky workaround to make it possible in the settings panel. Please let me know how it works out.

By the way, you may want to try re-calibrating your monitor or another color profile. We use a very low lightness value (11% ) on a dark hue (purple) with a low saturation (35%). It shouldn't look _that_ purple, and this is the first I've heard of it being too purple.

**Comment by czxtm** [comment]
Addressed by https://github.com/coopermaruyama/apathy-theme/commit/2368f41173a42ef8adb5701544c129e83d08fc08

**Comment by dvdzkwsk** [comment]
Wow awesome, that was fast; I'll definitely check it out. I was using One Dark UI, in fact I actually switched back to it from Isotope UI per your documentation recommendations.

It may just require some effort on my part to calibrate my monitors, so we'll see how that + the settings workaround end up doing. Thanks again!
